version: "3.8"

services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IrisDeploy
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    restart: unless-stopped
    
